const express = require("express");
const router = express.Router();

const authRoutes = require("./auth.routes");
const systemRoutes = require("./system.routes");
const dvRoutes = require("./don_vi.routes");
const userRoutes = require("./user.routes");
const danhmucRoutes = require("./danh_muc.routes");
const lcvRoutes = require("./loai_cong_viec.routes");
const spRoutes = require("./thong_tin_san_pham.routes");
const khoRoutes = require("./kho.routes");
const pbgRoutes = require("./phieu_ban_giao.routes");
const pmtRoutes = require("./phieu_muon_tra.routes");
const pbdRoutes = require("./phieu_bao_duong.routes");
const nkRoutes = require("./nhat_ky.routes");
const dashboardRoutes = require("./dashboard.routes");
const { verifyToken } = require("../middlewares/auth.middleware");

// Đăng ký các endpoints
router.use("/auth", authRoutes); // Thành: /api/auth/...
router.use("/system", verifyToken, systemRoutes); // Thành: /api/system/...
router.use("/dv", verifyToken, dvRoutes); // Thành: /api/system/...
router.use("/user", verifyToken, userRoutes); // Thành: /api/system/...
router.use("/dm", verifyToken, danhmucRoutes); // Thành: /api/system/...
router.use("/lcv", verifyToken, lcvRoutes); // Thành: /api/system/...
router.use("/sp", verifyToken, spRoutes); // Thành: /api/system/...
router.use("/kho", verifyToken, khoRoutes); // Thành: /api/system/...
router.use("/pbg", verifyToken, pbgRoutes); // Thành: /api/system/...
router.use("/pmt", verifyToken, pmtRoutes); // Thành: /api/system/...
router.use("/pbd", verifyToken, pbdRoutes); // Thành: /api/system/...
router.use("/nk", verifyToken, nkRoutes); // Thành: /api/system/...
router.use("/dashboard", verifyToken, dashboardRoutes); // Thành: /api/system/...

module.exports = router;
